// SPDX-License-Identifier: MIT OR Apache-2.0

//! # Description
//!
//! This crate offers several functionalities (not necessarily related to each other).
//! Please refer to the specific documentation for each part of the crate to learn more about it.
//!
//! # Features
//!
//! The crate splits its functionalities into several features, allowing to compile only the
//! parts that are needed.
//!
//! Some features build on top of others and enable them on their own, so requesting one is
//! enough to get everything it relies on:
//!
//! - `manifest` enables `paths`.
//! - `diesel` enables `postgres`.
//! - `diesel-async` enables `diesel`, and therefore `postgres` as well.
//!
//! `fmt`, `paths`, `parsing` and `universal-test-builder` do not enable any other feature.
//!
//! Note that `postgres`, `diesel` and `diesel-async` only contribute the database builders
//! inside `universal_test_builder::builders`. They do not enable `universal-test-builder`,
//! so they expose nothing unless it is requested alongside them.

#![cfg_attr(docsrs, feature(doc_cfg))]

// Allows code generated by `universal_test_builder`, which refers to this crate by name, to
// compile when the macro is used within the crate itself.
#[cfg(feature = "universal-test-builder")]
extern crate self as rustilities;

mod error;

#[cfg(feature = "paths")]
#[cfg_attr(docsrs, doc(cfg(feature = "paths")))]
pub mod paths;

#[cfg(feature = "fmt")]
#[cfg_attr(docsrs, doc(cfg(feature = "fmt")))]
pub mod fmt;

#[cfg(feature = "manifest")]
#[cfg_attr(docsrs, doc(cfg(feature = "manifest")))]
pub mod manifest;

#[cfg(feature = "parsing")]
#[cfg_attr(docsrs, doc(cfg(feature = "parsing")))]
pub mod parsing;

#[cfg(feature = "universal-test-builder")]
#[cfg_attr(docsrs, doc(cfg(feature = "universal-test-builder")))]
pub mod universal_test_builder;

pub use error::Error;
