// SPDX-License-Identifier: MIT OR Apache-2.0

#[cfg(feature = "universal-test-builder")]
mod universal_test_builder;

#[allow(unused_imports)]
use proc_macro::TokenStream;

/// Generates a fluent test builder from a list of `Builder`/`AsyncBuilder` units.
///
/// `#[universal_test_builder({builder = A}, {builder = B, async_builder})]` on a
/// `struct MyBuilder;` generates:
///
/// - `MyBuilder::default().with_a(args)` transition methods — the test requests the resources it
///   needs; unrequested resources are never built,
/// - `build()` (and `async_build()` when async builders are involved) producing a
///   `MyBuilderContext`.
/// - accessors `context.a()`/`context.a_mut()` over the resources generated by that context,
///   panicking with a clear message when the resource was not requested,
/// - `execute(|context| ...)`/`async_execute` to run the test body, and
/// - a `Drop` impl calling each builder's `on_drop` cleanup.
///
/// NOTE: The sync `build()` method cannot run async builders — they will produce `None` in the
/// context. Use `async_build()` when async builders are involved.
///
/// # Examples
///
/// ## Sync builders
/// ```
/// use rustilities::universal_test_builder::{
///     builders::{rustup_component::RustupComponent, temp_dir::TempDir},
///     universal_test_builder, Builder
/// };
///
/// #[universal_test_builder({builder = TempDir}, {builder = RustupComponent})]
/// struct MyTestBuilder;
///
/// MyTestBuilder::default()
///     .with_temp_dir(())
///     .build()
///     .execute(|context| {
///         assert!(context.temp_dir().path().is_dir());
///         // `rustup_component` was not requested: it was never built, and calling
///         // `context.rustup_component()` would panic with a clear message.
///         assert!(context.rustup_component.is_none());
///     });
/// ```
///
/// ## Async builders
/// With async builders, `async_build()` runs everything — and plain `build()` is still
/// available: it simply leaves the async outputs unbuilt (`None`):
/// ```
/// #[tokio::main(flavor = "current_thread")]
/// async fn main() {
///     use rustilities::universal_test_builder::{
///         AsyncBuilder, Builder, async_trait, builders::temp_dir::TempDir, universal_test_builder,
///     };
///
///     struct Answer;
///
///     #[async_trait]
///     impl AsyncBuilder for Answer {
///         type Args = u32;
///         type Output = u32;
///
///         async fn async_build(args: Self::Args) -> Self::Output {
///             args
///         }
///     }
///
///     #[universal_test_builder({builder = TempDir}, {builder = Answer, async_builder})]
///     struct MyTestBuilder;
///
///     // As an async builder is declared, it's possible to use `async_build/execute`
///     MyTestBuilder::default()
///         .with_temp_dir(())
///         .with_answer(42)
///         .async_build()
///         .await
///         .async_execute(|context| async move {
///             assert_eq!(*context.answer(), 42);
///             assert!(context.temp_dir().path().is_dir());
///         })
///         .await;
///
///     // But also just perform a sync build and execution: the async output stays unbuilt.
///     MyTestBuilder::default().with_temp_dir(()).build().execute(|context| {
///         assert!(context.temp_dir().path().is_dir());
///         assert!(context.answer.is_none());
///     });
/// }
/// ```
#[cfg(feature = "universal-test-builder")]
#[proc_macro_attribute]
pub fn universal_test_builder(attrs: TokenStream, item: TokenStream) -> TokenStream {
	universal_test_builder::universal_test_builder(attrs, item)
}
